### ISSUE TITLE
Microsoft Graph not working

### ISSUE THREAD

**Issue by krambos** [projectsend/projectsend#1336]
Versions
-----------

PHP: 8.3
OS: Ubuntu Server 24,04 LTS

Microsoft Graph is not working when enabled. I created an App Registration in Azure, provided the ID, key and tenant id (also tried with tenant domain since you don't clearly specify if you indeed need the tenant id), but when clicking the "windows" button in the login page I get redirected back to the same login page. Also tried enclosing everything in double and single quotes just in case.

Enabled logging through the sys.config.php, hybridauth.php, and php.ini (display_errors = On) files but no errors are produced or visible in the page.

Suggestion: Update the documentation to reflect setting up an App Registrations and configuring it properly in ProjectSend IF the settings are not what are suggested by the UI (i.e., defaults with just a secret creation and redirect URI)

**Comment by ThibautPr** [comment]
Hello, 

I confirm. Windows Button don't works. Works without line "log_in_required($allowed_levels);" from the process.php file.

Please update code and documentation.

**Comment by mdiermaier** [comment]
I can confirm it does not work when using the standard docker compose settings. 

When uncommenting "log_in_required($allowed_levels);" within the docker container I can at least once trigger the Azure sign in, but nothing happens afterwards.

**Comment by ignacionelson** [comment]
Hi everyone. The fatal error should be solved here
https://github.com/projectsend/projectsend/commit/caf6824fcf86952ceee0f26c7eeb7b91b8b0e732

The MS sign in not working might be an issue with something outdated in hybridauth

**Comment by andreaspichler23** [comment]
Hi everyone! We encountered the same problem, it would be beneficial to us to have a fix :)

**Comment by Trapulo** [comment]
same problem here

**Comment by QDTSys** [comment]
Hi, I have the same problem. First I have seen the screen to approve new application on O365 Account but now if I click on Windows button the home page reload, do you have find a solution ?

**Comment by KatieSanboxe** [comment]
Hello everyone,

Any update on this bug yet? Anyone make it work with MS Graph (Azure) successfully? Thanks

**Comment by KatieSanboxe** [comment]
Anyway, I've found a work-around for this bug which requiring manual adding of the user email in-advance and then it's good to go

**Comment by russr999** [comment]
Any update on how to fix this?

**Comment by KatieSanboxe** [comment]
> Any update on how to fix this?

@russr999  You have 2 options: 1st is the permanent fix which described by @peepsmn above, which I think is a good fix. 2nd is the work-around I mentioned earlier, which is keep using the External login but you manually create the user (with same email from external login source) and then when you click on External login everything is fine

**Comment by AbdoEddy** [comment]
you get redirected to the same login page because the user is not yet approved from admin on the system. when you approve the user it should connect.
on my end i fixed the hybrid auth code to resolve this, we directly configured these critical Entra ID parameters within the Hybridauth setup file (includes/hybridauth.php). By embedding the correct credentials and tenant information at this level, we ensured that Hybridauth had the precise details required to communicate effectively with Entra ID, exchange the authentication code for a valid token, and retrieve user information.

**Comment by riukira90** [comment]
Hi @AbdoEddy, I need some help. I'm having issues with Microsoft Graph. As other users mentioned above, after upgrading from version 1720 to 1945, the Microsoft Graph authentication stopped working.  
I tried every possible solution mentioned above and checked all the parameters, but the problem persists.  

I'm now trying your solution, modifying the hybridauth.php file, but I don’t understand how to set the app registration parameters directly in the file.  

Thank you for your support.
